web/router.ex
defmodule Finch.Router do
  @moduledoc """
  Where it all begins. Mega exciting.
  """

  use Finch.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  scope "/", Finch do
    pipe_through :browser

    resources "/session", SessionController,
      only: ~w(new create delete)a,
      singleton: true

    resources "/bundles", BundleController, except: ~w(update edit delete)a do
      post "/entry", BundleEntryController, :create, as: :entry
    end
    resources "/items", ItemController, only: ~w(index create)a

    get "/*path", PageController, :show
  end
end

web/views/layout_view.ex
defmodule Finch.LayoutView do
  @moduledoc false
  use Finch.Web, :view

  def page_title(conn, assigns) do
    # TODO: Work out how to do this nicely
    assigns = assigns |> Dict.put :view_template, view_template(conn)
    conn
    |> view_module
    |> render_existing( "page_title", assigns )
    |> case do
      nil   -> "Finch"
      title -> title
    end
  end

  def prefixed_page_title(conn, assigns) do
    title = page_title( conn, assigns )
    case title do
      "Finch" -> "Finch"
      title   -> "Finch - #{title}"
    end
  end

  def current_user(conn) do
    Plug.Conn.get_session(conn, :current_user)
  end
end

web/templates/layout/_drawer.html.eex
<div class="mdl-layout__drawer">
  <span class="mdl-layout-title">
    <%= link "Finch", to: "/" %>
  </span>
  <nav class="mdl-navigation">
    <a class="mdl-navigation__link" href="<%= bundle_path(@conn, :index) %>">
      Bundles
    </a>
    <a class="mdl-navigation__link" href="<%= item_path(@conn, :index) %>">
      Items
    </a>
  </nav>
</div>

web/templates/layout/_flashes.html.eex
<div class="alert--info"  role="alert">
  <%= get_flash(@conn, :info) %>
</div>
<div class="alert--error" role="alert">
  <%= get_flash(@conn, :error) %>
</div>

web/templates/layout/_header.html.eex
<header class="mdl-layout__header">
  <div class="mdl-layout__header-row">
    <span class="mdl-layout-title">
      <%= link page_title(@conn, assigns), to: "/" %>
    </span>
    <div class="mdl-layout-spacer"></div>
    <% user = current_user @conn %>
    <%= if user do %>
      <%= link "Log out", to: session_path(@conn, :delete), method: :delete %>
    <%= else %>
      <%= link "Sign in", to: session_path(@conn, :new) %>
    <% end %>
  </div>
</header>

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title><%= prefixed_page_title(@conn, assigns) %></title>

    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  </head>

  <body>
    <div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
      <%= render "_header.html", conn: @conn %>
      <%= render "_drawer.html", conn: @conn %>
      <%= render "_flashes.html", conn: @conn %>

      <main class="page__content">
        <%= @inner %>
      </main>

    </div>

    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>