web/router.ex
defmodule Finch.Router do
  @moduledoc """
  Where it all begins. Mega exciting.
  """

  use Finch.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  scope "/", Finch do
    pipe_through :browser

    resources "/session", SessionController,
      only: ~w(new create delete)a,
      singleton: true

    resources "/bundles", BundleController, except: ~w(update edit delete)a do
      post "/entry", BundleEntryController, :create, as: :entry
    end
    resources "/items", ItemController, only: ~w(index create)a

    get "/*path", PageController, :show
  end
end

web/models/bundle_entry.ex
defmodule Finch.BundleEntry do
  @moduledoc """
  A join between Bundles and Items.
  """

  use Finch.Web, :model

  schema "bundle_entries" do
    belongs_to :bundle, Finch.Bundle
    belongs_to :item,   Finch.Item
    timestamps
  end

  @required_fields ~w(bundle_id item_id)
  @optional_fields ~w()


  @doc """
  Creates a changeset based on the `model` and `params`.

  If no params are provided, an invalid changeset is returned
  with no validation performed.
  """
  def changeset do
    %__MODULE__{} |> changeset
  end
  def changeset(model, params \\ :empty) do
    model
    |> cast(params, @required_fields, @optional_fields)
    |> unique_constraint(
        :bundle,
        name: "bundle_entries_bundle_id_item_id_index",
        message: "already contains this item",
      )
  end
end

web/controllers/bundle_entry_controller.ex
defmodule Finch.BundleEntryController do
  @moduledoc """
  We can CRUD bundles!
  """
  use Finch.Web, :controller
  alias Finch.Bundle
  alias Finch.BundleEntry

  plug :scrub_params, "bundle_entry" when action in [:create]

  def create(conn, %{"bundle_id" => bundle_code, "bundle_entry" => x}) do
    bundle = Bundle |> Repo.get_by!( code: bundle_code )
    item_id = x["item_id"]
    attrs   = %{ bundle_id: bundle.id, item_id: item_id }
    %BundleEntry{}
    |> BundleEntry.changeset(attrs)
    |> Repo.insert
    |> case do
      {:ok, _} ->
        conn
        |> put_flash(:info, "Item added successfully.")
        |> redirect(to: bundle_path(conn, :show, bundle.code))

      {:error, _} ->
        conn
        |> put_flash(:info, "Cannot add this Item.")
        |> redirect(to: bundle_path(conn, :show, bundle.code))
    end
  end
end

web/views/bundle_entry_view.ex
defmodule Finch.BundleEntryView do
  @moduledoc false
  use Finch.Web, :view
end

web/templates/bundle_entry/new.html.eex
<h4>Add an Item</h4>

<%= form_for @changeset, bundle_entry_path(@conn, :create, @bundle), fn f -> %>
<%= if @changeset.action do %>
  <div class="alert--danger">
    <p>Oops, something went wrong! Please check the errors below:</p>
    <ul>
      <%= for {attr, message} <- f.errors do %>
        <li><%= humanize(attr) %> <%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div>
  <div class="textfield mdl-js-textfield">
    <%= hidden_input f, :item_id, id: "datalist-reciever" %>
    <input class="mdl-textfield__input" id="datalist-input" list="datalist-data" type="text">
    <%= label f, :item_id, "Item", class: "mdl-textfield__label" %>
  </div>
</div>

<datalist id="datalist-data">
  <%= for {item, id} <- @items do %>
    <option value="<%= item %>"><%= id %></option>
  <% end %>
</datalist>

<script type="text/javascript" charset="utf-8">
window.datalistPage = true;
</script>

<div class="foot-nav">
  <%= submit "Submit" %>
</div>
<% end %>